name: Build

on:
  push:
    branches:
    - feature/dev
  workflow_dispatch:


jobs:
  darwin:
    name: Darwin ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
        - arch: amd64
          runner: macos-15-intel
        - arch: arm64
          runner: macos-15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"

    - name: Build
      env:
        GOOS: darwin
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: "1"
      run: |
        mkdir -p docs/assets/darwin/${GOARCH}

        go build \
          -buildmode=c-shared \
          -o docs/assets/darwin/${GOARCH}/libbip0039.dylib \
          ./share

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: darwin-${{ matrix.arch }}
        path: docs/assets/darwin/${{ matrix.arch }}/

  linux:
    name: Linux ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
        - arch: amd64
          runner: ubuntu-24.04
        - arch: arm64
          runner: ubuntu-24.04-arm

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"

    - name: Build
      env:
        GOOS: linux
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: "1"
      run: |
        mkdir -p docs/assets/linux/${GOARCH}

        go build \
          -buildmode=c-shared \
          -o docs/assets/linux/${GOARCH}/libbip0039.so \
          ./share

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-${{ matrix.arch }}
        path: docs/assets/linux/${{ matrix.arch }}/

  windows:
    name: Windows ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: amd64
          runner: windows-latest

        - arch: arm64
          runner: windows-11-vs2026-arm

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"

    - name: Build Windows AMD64
      if: matrix.arch == 'amd64'
      shell: bash
      env:
        GOOS: windows
        GOARCH: amd64
        CGO_ENABLED: "1"
      run: |
        mkdir -p docs/assets/windows/amd64

        go build \
          -buildmode=c-shared \
          -o docs/assets/windows/amd64/bip0039.dll \
          ./share

    - name: Build Windows ARM64
      if: matrix.arch == 'arm64'
      shell: msys2 {0}
      env:
        GOOS: windows
        GOARCH: arm64
        CGO_ENABLED: "1"
        CC: clang
        CXX: clang++
      run: |
        echo "MSYSTEM=$MSYSTEM"

        echo "Clang:"
        which clang
        clang --version

        echo "Target:"
        clang -print-target-triple

        echo "Go:"
        go version
        go env GOOS GOARCH GOHOSTOS GOHOSTARCH CGO_ENABLED CC CXX

        mkdir -p docs/assets/windows/arm64

        go build \
          -buildmode=c-shared \
          -o docs/assets/windows/arm64/bip0039.dll \
          ./share

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.arch }}
        path: docs/assets/windows/${{ matrix.arch }}/
